### ISSUE TITLE
steal-tools build already part of donejs generators

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs-cordova#1]
These lines https://github.com/donejs/donejs-cordova/blob/master/lib/template.js#L1-L7 aren't needed if you are doing an append. Those will already be in the build.js

**Comment by phillipskevin** [comment]
Ok, I'll check if the build.js already exists and conditionally add those lines.

**Comment by phillipskevin** [comment]
This has been closed in https://github.com/donejs/donejs-cordova/pull/5
