### ISSUE TITLE
Warning when using DoneJS app on iOS Simulator 

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs-cordova#16]
The first time you run a DoneJS app on the ios-sim, you get this scary warning:

![image](https://cloud.githubusercontent.com/assets/5851984/21916212/9f8e73ac-d904-11e6-8160-67b6aeb9b728.png)

**Comment by matthewp** [comment]
Some links:

* https://forums.xamarin.com/discussion/81425/ios-10-1-message-app-may-slow-down-your-iphone
* https://forum.ionicframework.com/t/my-app-may-slow-down-your-iphone-the-developer-of-this-app-bla-bla/70624/5

Maybe updating to latest Cordova will fix it.

**Comment by matthewp** [comment]
This doesn't happen in steal-cordova@alpha, upgrading the cordova version fixes it.
